apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-app
spec:
  serviceName: node-app-headless
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: node:18-alpine
          ports:
            - containerPort: 3000

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

          volumeMounts:
            - name: data
              mountPath: /usr/src/app/data
            - name: cache
              mountPath: /usr/src/app/cache

      volumes:
        - name: cache
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
